spring:
  application:
    name : myfirstwebapp

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: yyyy-MM-dd

  jpa:
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
logging:
  level:
    org:
      springframework: info
    com:
      udemy:
        springboot:
          myfirstwebapp: info
