spring:
  application:
    name: restful-web-services

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true

#    show-sql: true

  security:
    user:
      name: sai
      password: sai123

  datasource:
    url: jdbc:h2:mem:testdb
logging:
  level:
    org:
      springframework: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
