spring:
  application:
    name: learn-spring-security

  datasource:
    url: jdbc:h2:mem:testdb
#  security:
#    user:
#      name: sai
#      password: prajith
logging:
  level:
    org:
      springframework:
         security: debug